Microsoft Windows [版本 10.0.17763.737]                                                                                (c) 2018 Microsoft Corporation。保留所有权利。                                                                                                                                                                                                                             C:\Users\huseph\Desktop\python>python test.py                                                                            File "test.py", line 43                                                                                                  for i in range(1,5)                                                                                                                      ^                                                                                                SyntaxError: invalid syntax                                                                                                                                                                                                                   C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 79, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 61, in lets_roll                                                                                    ch_num1= html.find('href="/member/Itsuki-chan/characters/', ch_num1) + 37                                          UnboundLocalError: local variable 'ch_num1' referenced before assignment                                                                                                                                                                                                            C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 79, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 61, in lets_roll                                                                                    ch_num1= html.find('href="/member/Itsuki-chan/characters/', ch_num1) + 37                                          TypeError: argument should be integer or bytes-like object, not 'str'                                                                                                                       C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 79, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 61, in lets_roll                                                                                    ch_num1= html.find('href="/member/Itsuki-chan/characters/', ch_num1) + 37                                          TypeError: argument should be integer or bytes-like object, not 'str'                                                                                                                       

 C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 79, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 61, in lets_roll                                                                                    ch_num1= int(html.find('href="/member/Itsuki-chan/characters/', ch_num1)) + 37                                     TypeError: argument should be integer or bytes-like object, not 'str'                                                                                                                                                                         C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 79, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 66, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 44, in character                                                                                    html += url_open(url_ch + str(i))                                                                                  UnboundLocalError: local variable 'html' referenced before assignment                                                                                                                                                                         C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 80, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 67, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 45, in character                                                                                    html += url_open(url_ch + str(i))                                                                                    File "test.py", line 15, in url_open                                                                                     response = urllib.request.urlopen(url)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen                return opener.open(url, data, timeout)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open                   response = meth(req, response)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response          'http', request, response, code, msg, hdrs)                                                                          File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error                  return self._call_chain(*args)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain            result = func(*args)                                                                                                 File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                 urllib.error.HTTPError: HTTP Error 404: Not Found                                                                                                                                                                                             C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 80, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 67, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 45, in character                                                                                    html += url_open(url_ch + str(i))                                                                                    File "test.py", line 15, in url_open                                                                                     response = urllib.request.urlopen(url)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen                return opener.open(url, data, timeout)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open                   response = meth(req, response)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response          'http', request, response, code, msg, hdrs)                                                                          File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error                  return self._call_chain(*args)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain            result = func(*args)                                                                                                 File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                 urllib.error.HTTPError: HTTP Error 404: Not Found                                                                                                                                                                                             C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/api/member/126641/characters/b'118'/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                         Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 46, in character                                                                                    html += url_open(url_ch + str(i))                                                                                    File "test.py", line 15, in url_open                                                                                     response = urllib.request.urlopen(url)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen                return opener.open(url, data, timeout)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open                   response = meth(req, response)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response          'http', request, response, code, msg, hdrs)                                                                          File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error                  return self._call_chain(*args)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain            result = func(*args)                                                                                                 File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                 urllib.error.HTTPError: HTTP Error 404: Not Found                                                                                                                                                                                             C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             这是url:: https://worldcosplay.net/api/member/126641/characters/b'118'/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                         Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 46, in character                                                                                    html += url_open(url_ch + str(i))                                                                                    File "test.py", line 16, in url_open                                                                                     response = urllib.request.urlopen(url)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen                return opener.open(url, data, timeout)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open                   response = meth(req, response)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response          'http', request, response, code, msg, hdrs)                                                                          File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error                  return self._call_chain(*args)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain            result = func(*args)                                                                                                 File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                 urllib.error.HTTPError: HTTP Error 404: Not Found                                                                                                                                                                                             C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 43, in character                                                                                    url_ch = 'https://worldcosplay.net/api/member/126641/characters/' + ch_num + '/photos.json?limit=16&p3_photo_list=true&page='                                                                                                             TypeError: can only concatenate str (not "bytes") to str                                                                                                                                                                                      C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 82, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 60, in lets_roll                                                                                    os.mkdir('Itsuki-chan')                                                                                            FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'Itsuki-chan'                                                                                                                                                               C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             b'118'                                                                                                                 这是url:: https://worldcosplay.net/api/member/126641/characters/b'118'/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                         Traceback (most recent call last):                                                                                       File "test.py", line 82, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 69, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 47, in character                                                                                    html += url_open(url_ch + str(i))                                                                                    File "test.py", line 16, in url_open                                                                                     response = urllib.request.urlopen(url)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen                return opener.open(url, data, timeout)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open                   response = self._open(req, data)                                                                                     File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open                  '_open', req)                                                                                                        File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain            result = func(*args)                                                                                                 File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1360, in https_open            context=self._context, check_hostname=self._check_hostname)                                                          File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1317, in do_open               encode_chunked=req.has_header('Transfer-encoding'))                                                                  File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1244, in request                  self._send_request(method, url, body, headers, encode_chunked)                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1290, in _send_request            self.endheaders(body, encode_chunked=encode_chunked)                                                                 File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1239, in endheaders               self._send_output(message_body, encode_chunked=encode_chunked)                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output             self.send(msg)                                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send                      self.connect()                                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1414, in connect                  server_hostname=server_hostname)                                                                                     File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 423, in wrap_socket                       session=session                                                                                                      File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 870, in _create                           self.do_handshake()                                                                                                  File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake                     self._sslobj.do_handshake()                                                                                        KeyboardInterrupt                                                                                                                                                                                                                             C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 82, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 60, in lets_roll                                                                                    os.mkdir('Itsuki-chan')                                                                                            FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'Itsuki-chan'                                                                                                                                                               C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             <class 'bytes'>                                                                                                        这是url:: https://worldcosplay.net/api/member/126641/characters/b'118'/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                         Traceback (most recent call last):                                                                                       File "test.py", line 82, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 69, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 47, in character                                                                                    html += url_open(url_ch + str(i))                                                                                    File "test.py", line 16, in url_open                                                                                     response = urllib.request.urlopen(url)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen                return opener.open(url, data, timeout)                                                                               File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open                   response = meth(req, response)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response          'http', request, response, code, msg, hdrs)                                                                          File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error                  return self._call_chain(*args)                                                                                       File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain            result = func(*args)                                                                                                 File "C:\Users\huseph\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default     raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                 urllib.error.HTTPError: HTTP Error 404: Not Found                                                                                                                                                                                             C:\Users\huseph\Desktop\python>python test.py                                                                            File "test.py", line 61                                                                                                  os.chdir('Itsuki-chan')                                                                                                 ^                                                                                                                 SyntaxError: invalid syntax                                                                                                                                                                                                                   C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 59, in lets_roll                                                                                    os.mkdir('Itsuki-chan')                                                                                            FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'Itsuki-chan'                                                                                                                                                               C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             <class 'bytes'>                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 44, in character                                                                                    url_ch = 'https://worldcosplay.net/api/member/126641/characters/' + str(ch_num, encoding = 'urf-8') + '/photos.json?limit=16&p3_photo_list=true&page='                                                                                    LookupError: unknown encoding: urf-8                                                                                                                                                                                                          C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             <class 'bytes'>                                                                                                        这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                            Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 47, in character                                                                                    html += url_open(url_ch + str(i))                                                                                  TypeError: can only concatenate str (not "bytes") to str                                                                                                                                                                                      C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             <class 'str'>                                                                                                          Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 44, in character                                                                                    url_ch = 'https://worldcosplay.net/api/member/126641/characters/' + str(ch_num, encoding = 'utf-8') + '/photos.json?limit=16&p3_photo_list=true&page='                                                                                    TypeError: decoding str is not supported                                                                                                                                                                                                      C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 59, in lets_roll                                                                                    os.mkdir('Itsuki-chan')                                                                                            FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'Itsuki-chan'                                                                                                                                                               C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             <class 'str'>                                                                                                          这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                            这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=2                                                                                                                            这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=3                                                                                                                            这是url:: https://worldcosplay.net/photo/6859679                                                                                                                                                                                              Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 52, in character                                                                                    get_img(html[img_num1: img_num2])                                                                                    File "test.py", line 27, in get_img                                                                                      url_img = html[img_num1, img_num2]                                                                                 TypeError: byte indices must be integers or slices, not tuple                                                                                                                                                                                 C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 59, in lets_roll                                                                                    os.mkdir('Itsuki-chan')                                                                                            FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'Itsuki-chan'                                                                                                                                                               C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             <class 'str'>                                                                                                          这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                            这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=2                                                                                                                            这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=3                                                                                                                            这是url:: https://worldcosplay.net/photo/6859679                                                                                                                                                                                              Traceback (most recent call last):                                                                                       File "test.py", line 81, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 68, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 52, in character                                                                                    get_img(html[img_num1: img_num2])                                                                                    File "test.py", line 27, in get_img                                                                                      url_img = html[img_num1, img_num2]                                                                                 TypeError: string indices must be integers                                                                                                                                                                                                    C:\Users\huseph\Desktop\python>python test.py                                                                          正在爬取图片...                                                                                                        这是url:: https://worldcosplay.net/member/Itsuki-chan/characters/                                                                                                                                                                             <class 'str'>                                                                                                          这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=1                                                                                                                            这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=2                                                                                                                            这是url:: https://worldcosplay.net/api/member/126641/characters/118/photos.json?limit=16&p3_photo_list=true&page=3                                                                                                                            这是url:: https://worldcosplay.net/photo/6859679                                                                                                                                                                                              我在get_img里： <class 'int'> 12522                                                                                    Traceback (most recent call last):                                                                                       File "test.py", line 82, in <module>                                                                                     lets_roll()                                                                                                          File "test.py", line 69, in lets_roll                                                                                    character(html[ch_num1: ch_num2], html[ch_name1: ch_name2])                                                          File "test.py", line 53, in character                                                                                    get_img(html[img_num1: img_num2])                                                                                    File "test.py", line 28, in get_img                                                                                      url_img = html[img_num1, img_num2]                                                                                 TypeError: string indices must be integers                                                                                                                   


这是简单的语法错误！！！！！应该为：string[123  : 456] 
用冒号！！！！


出错原因：找不到后确实返回-1，但我直接给他加了5，应该在while下写头指针+5的！！先让它过一下while判断是否符合！！！！